name: Build Kade Engine + Release
run-name: Kade-Engine Mobile Port
on: workflow_dispatch

permissions:
  contents: write
  discussions: write

env:
  PROJECT_NAME: "Kade Engine"
  REPO_PATH: PsychEngine-report/Kade-Engine

jobs:
  get-commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.COMMIT_HASH }}
    steps:
      - name: Check Repository
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPO_PATH: ${{ env.REPO_PATH }}"
          if [[ "$GITHUB_REPOSITORY" != "${{ env.REPO_PATH }}" ]]; then
            echo "Doesn't seem to be correct, returning SIGABRT..."
            exit 6
          else
            echo "Seems to be correct..."
          fi

      - name: Get latest commit hash
        id: get_commit_hash
        run: |
          commit_hash=${GITHUB_SHA::7}
          echo "Latest commit hash is $commit_hash"
          echo "::set-output name=COMMIT_HASH::$commit_hash"

  build:
    name: ${{ matrix.name }}
    needs: get-commit-hash
    strategy:
      matrix:
        include:
          - name: Windows X64
            os: windows-2022
            setupCommand: ./setup/windows.bat
            buildArgs: "windows -D officialBuild -D HXCPP_M64 -final -release"
            artifactName: windowsBuild64
            artifactPath: export/release/windows/bin/*
            system: Windows
          - name: Windows X32
            os: windows-2022
            setupCommand: ./setup/windows.bat
            buildArgs: "windows -D officialBuild -D HXCPP_M32 -final -release"
            artifactName: windowsBuild32
            artifactPath: export/release/windows/bin/*
            system: Windows
          - name: Linux
            os: ubuntu-24.04
            buildArgs: "linux -D officialBuild -final -release"
            artifactName: Linux
            artifactPath: export/release/linux/bin/*
            system: Linux
          - name: MacOS
            os: macos-15
            buildArgs: "mac -D officialBuild -final -release"
            artifactName: MacOS
            artifactPath: export/release/macos/bin/*
            system: MacOS
          - name: Html5
            os: ubuntu-24.04
            buildArgs: "html5 -D officialBuild -final -release"
            artifactName: HTML5
            artifactPath: export/release/html5/bin/*
            system: Html5
          - name: Android
            os: ubuntu-24.04
            buildArgs: "android -D officialBuild -final -release" 
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
            system: Android
          - name: iOS
            os: macos-15
            setupCommand: sh ./setup/unix.sh
            buildArgs: "ios -final -nosign -D officialBuild -release"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
            system: iOS
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        setupCommand: ${{ matrix.setupCommand }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
        system: ${{ matrix.system }}

  Releaser:
    needs: [get-commit-hash, build]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: androidBuild
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-MobilePad-Update.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
          name: iOSBuild
          path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa

      - name: Download Windows Build
        uses: actions/download-artifact@main
        with:
          name: windowsBuild64
          path: /home/runner/windowsBuild64

      - name: Zip Windows 64 Build For Release
        run: |
          cd /home/runner/windowsBuild64
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-X64.zip" .

      - name: Download WindowsX32 Build
        uses: actions/download-artifact@main
        with:
          name: windowsBuild32
          path: /home/runner/windowsBuild32

      - name: Zip Windows 32 Build For Release
        run: |
          cd /home/runner/windowsBuild32
          zip -r "/home/runner/${{ env.PROJECT_NAME }}-Windows-X32.zip" .

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "DevBuild ${{ needs.get-commit-hash.outputs.commit_hash }}"
          tag_name: "devbuild-${{ needs.get-commit-hash.outputs.commit_hash }}"
          make_latest: true
          #prerelease: false
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
            /home/runner/*.zip
            /home/runner/*.zip
